version: "3"
services:
  exporter:
    image: local/veeam-ahvproxy-exporter
    build: .
    command:
      - "-log.level=DEBUG"
      - "-exporter.conf=/config.yml"
    ports:
      - 9405:9405
    volumes:
      - ./config.yml:/config.yml
