version: "3"
services:
  exporter:
    image: claranet/veeam-ahvproxy-exporter
    build: .
    command:
      - "-log.level=DEBUG"
      - "-exporter.conf=/config.yml"
    ports:
      - 9760:9760
    volumes:
      - ./config.yml:/config.yml
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
